version: "3.7"

services:
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - /usr/app/src/node_modules
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - TZ=Asia/Ho_Chi_Minh
